# Generated by Django 5.2.8 on 2025-11-25 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=100)),
                ('duration_days', models.IntegerField()),
                ('duration_nights', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overview', models.TextField()),
                ('image', models.ImageField(upload_to='packages/')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('activity', models.TextField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='packages.package')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
    ]
