# Generated by Django 4.2.27 on 2026-08-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('SUITE', 'Suite'), ('FAMILY', 'Family'), ('DELUXE', 'Deluxe')], max_length=10),
        ),
    ]
