# Generated by Django 4.2.27 on 2026-08-13 14:04

from django.db import migrations


def migrate_booking_relations(apps, schema_editor):
    Booking = apps.get_model('bookings', 'Booking')
    for booking in Booking.objects.all():
        if booking.content_type and booking.object_id:
            model_name = booking.content_type.model
            if model_name == 'flight':
                booking.flight_id = booking.object_id
            elif model_name == 'room':
                booking.room_id = booking.object_id
            elif model_name == 'package':
                booking.package_id = booking.object_id
            booking.save()

def reverse_migrate_booking_relations(apps, schema_editor):
    Booking = apps.get_model('bookings', 'Booking')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    for booking in Booking.objects.all():
        if booking.flight_id:
            ct = ContentType.objects.get(app_label='flights', model='flight')
            booking.content_type = ct
            booking.object_id = booking.flight_id
        elif booking.room_id:
            ct = ContentType.objects.get(app_label='hotels', model='room')
            booking.content_type = ct
            booking.object_id = booking.room_id
        elif booking.package_id:
            ct = ContentType.objects.get(app_label='packages', model='package')
            booking.content_type = ct
            booking.object_id = booking.package_id
        booking.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_flight_booking_package_booking_room_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_booking_relations, reverse_migrate_booking_relations)
    ]
