# Generated by Django 4.2.27 on 2026-08-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20260813_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='object_id',
        ),
    ]
