# Generated by Django 4.2.27 on 2026-08-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_booking_content_type_remove_booking_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_tran_id',
            field=models.CharField(blank=True, help_text='Bank Transaction ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='val_id',
            field=models.CharField(blank=True, help_text='SSLCommerz Validation ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('SSLCOMMERZ', 'SSLCommerz (bKash, Cards, NetBanking)'), ('BKASH', 'bKash (Manual)'), ('NAGAD', 'Nagad (Manual)'), ('VISA', 'Visa (Manual)'), ('MASTERCARD', 'MasterCard (Manual)')], default='SSLCOMMERZ', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Gateway Transaction ID (tran_id)', max_length=100, null=True),
        ),
    ]
